### ISSUE TITLE
Extra ces

### ISSUE THREAD

**Issue by JackyboyButler** [xXNiceYT/CustomEnchants#1]
How do i add extra ces?

**Comment by xXNiceYT** [comment]
public function init(){
		PMEnchantment::registerEnchantment(new PMEnchantment(self::LIFESTEAL, "Lifesteal", PMEnchantment::RARITY_COMMON, PMEnchantment::SLOT_SWORD, PMEnchantment::SLOT_NONE, 5));
		new LifeSteal();
	}
